#include "PT/ScenePackage.h"
#include <stb/stb_image.h>
#include <glm/gtc/matrix_transform.hpp>
#include <filesystem>
#include <fstream>
#include <map>
#include <cstring>
#include <cmath>
#include <stdexcept>
#include <chrono>
#include <tuple>
namespace pt {
namespace {
using Json=nlohmann::json;
glm::vec3 vector(const Json &j){auto a=j.get<std::array<float,3>>();for(float x:a)if(!std::isfinite(x))throw std::invalid_argument("PT package: non-finite vector");return {a[0],a[1],a[2]};}
glm::mat4 matrix(const Json &j){auto a=j.get<std::array<float,16>>();glm::mat4 m;for(int i=0;i<16;++i){if(!std::isfinite(a[i]))throw std::invalid_argument("PT package: non-finite matrix");m[i/4][i%4]=a[i];}return m;}
std::filesystem::path local(const std::filesystem::path &root,const Json &value){auto p=std::filesystem::path(value.get<std::string>());if(p.empty()||p.is_absolute())throw std::invalid_argument("PT package: expected a relative asset path");for(const auto &part:p)if(part=="..")throw std::invalid_argument("PT package: parent asset traversal");auto resolved=std::filesystem::weakly_canonical(root/p);auto relative=resolved.lexically_relative(std::filesystem::weakly_canonical(root));if(relative.empty()||*relative.begin()=="..")throw std::invalid_argument("PT package: asset escapes package");return resolved;}
std::vector<float> floats(const std::filesystem::path &path,uint64_t offset,uint64_t count){if(count>uint64_t(1)<<28)throw std::length_error("PT package: oversized float buffer");auto bytes=std::filesystem::file_size(path);if(offset>bytes||count>(bytes-offset)/4)throw std::invalid_argument("PT package: truncated float buffer");std::ifstream f(path,std::ios::binary);f.seekg(offset);std::vector<float> a(count);f.read(reinterpret_cast<char*>(a.data()),std::streamsize(count*4));if(!f)throw std::runtime_error("PT package: cannot read float buffer");for(float x:a)if(!std::isfinite(x))throw std::invalid_argument("PT package: non-finite float buffer");return a;}
}
ScenePackage loadScenePackage(const std::string &path,uint32_t width,uint32_t height){
    const auto started=std::chrono::steady_clock::now();double textureSeconds=0,geometrySeconds=0;
    uint32_t endian=1;if(*reinterpret_cast<uint8_t*>(&endian)!=1)throw std::runtime_error("PT package: little-endian host required");
    if(!width||!height||width>16384||height>16384)throw std::invalid_argument("PT package: invalid viewport");
    if(std::filesystem::file_size(path)>32*1024*1024)throw std::length_error("PT package: oversized manifest");std::ifstream input(path);Json j;input>>j;const auto manifestSeconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();
    if(j.at("format")!="SceneRenderer.PT.v1")throw std::invalid_argument("PT package: unsupported format");
    auto root=std::filesystem::path(path).parent_path();auto binary=local(root,j.at("geometry"));std::ifstream meshFile(binary,std::ios::binary);char magic[8];meshFile.read(magic,8);if(!meshFile||std::memcmp(magic,"PTMESH01",8))throw std::invalid_argument("PT package: invalid mesh header");
    std::filesystem::path tangentFile;if(j.contains("tangents")){tangentFile=local(root,j["tangents"]);std::ifstream f(tangentFile,std::ios::binary);char header[8];f.read(header,8);if(!f||std::memcmp(header,"PTTANG01",8))throw std::invalid_argument("PT package: invalid tangent header");}
    ScenePackage result;auto &s=result.snapshot;auto &frame=s.frame;frame.viewportWidth=width;frame.viewportHeight=height;frame.inverseSquareLocalLights=true;
    auto camera=matrix(j.at("camera").at("world")),projection=matrix(j.at("camera").at("projection"));float sourceAspect=j.at("camera").at("aspect").get<float>();if(!std::isfinite(sourceAspect)||sourceAspect<=0)throw std::invalid_argument("PT package: invalid camera aspect");projection[0][0]*=sourceAspect/(float(width)/height);
    if(std::abs(glm::determinant(camera))<1e-10f||std::abs(glm::determinant(projection))<1e-10f)throw std::invalid_argument("PT package: singular camera");
    glm::mat4 depth(1);depth[2][2]=.5f;depth[3][2]=.5f;frame.view=glm::inverse(camera);frame.viewProjection=depth*projection*frame.view;frame.cameraPosition=glm::vec3(camera[3]);s.exposure=j.value("exposure",1.f);if(!std::isfinite(s.exposure)||s.exposure<=0)throw std::invalid_argument("PT package: invalid exposure");
    std::map<std::string,std::shared_ptr<const render::ImageRGBA8>> images;
    auto image=[&](const Json &asset){auto p=local(root,asset).string();auto found=images.find(p);if(found!=images.end())return found->second;const auto textureStarted=std::chrono::steady_clock::now();int w=0,h=0,n=0;stbi_set_flip_vertically_on_load_thread(false);auto data=stbi_load(p.c_str(),&w,&h,&n,4);if(!data)throw std::runtime_error("PT package: cannot load image "+p);std::shared_ptr<render::ImageRGBA8> out;try{if(w<=0||h<=0||w>16384||h>16384)throw std::invalid_argument("PT package: invalid image dimensions");out=std::make_shared<render::ImageRGBA8>();out->width=w;out->height=h;out->pixels.assign(data,data+size_t(w)*h*4);}catch(...){stbi_image_free(data);throw;}stbi_image_free(data);images[p]=out;textureSeconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-textureStarted).count();return std::shared_ptr<const render::ImageRGBA8>(out);};
    std::vector<render::SnapshotDraw> materials;
    for(auto &m:j.at("materials")){render::SnapshotDraw draw;auto color=vector(m.at("base_color"));draw.parameters.albedoAlpha=glm::vec4(color,m.value("opacity",1.f));draw.parameters.factors={m.value("metallic",0.f),m.value("roughness",.8f),1,m.value("alpha_cutoff",0.f)};draw.parameters.emissiveNormal=glm::vec4(vector(m.value("emission",Json::array({0,0,0}))),0);draw.extension.settings.w=m.value("two_sided",false)?1:0;draw.pathTracingIor=m.value("ior",0.f);draw.pathTracingRoughness=m.value("dielectric_roughness",0.f);
        for(float x:{draw.parameters.albedoAlpha.w,draw.parameters.factors.x,draw.parameters.factors.y,draw.parameters.factors.w,draw.pathTracingRoughness})if(!std::isfinite(x)||x<0||x>1)throw std::invalid_argument("PT package: invalid material factor");
        if(glm::any(glm::lessThan(color,glm::vec3(0)))||glm::any(glm::greaterThan(color,glm::vec3(1)))||glm::any(glm::lessThan(glm::vec3(draw.parameters.emissiveNormal),glm::vec3(0)))||!std::isfinite(draw.pathTracingIor)||(draw.pathTracingIor!=0&&(draw.pathTracingIor<=1||draw.pathTracingIor>4)))throw std::invalid_argument("PT package: invalid material optics");
        auto model=m.value("bsdf_model",std::string("pbr"));if(model!="pbr"&&model!="lambert"&&model!="ggx_add"&&model!="thin_diffuse")throw std::invalid_argument("PT package: unsupported BSDF model");draw.pathTracingBsdfModel=model=="lambert"?1:model=="ggx_add"?2:model=="thin_diffuse"?3:0;
        draw.pathTracingKind=m.value("thin_dielectric",false)?5:(m.value("bounded_volume",false)?4:0);
        draw.pathTracingAbsorption=vector(m.value("absorption",Json::array({0,0,0})));draw.pathTracingScattering=vector(m.value("scattering",Json::array({0,0,0})));draw.pathTracingAnisotropy=m.value("anisotropy",0.f);
        if(glm::any(glm::lessThan(draw.pathTracingAbsorption,glm::vec3(0)))||glm::any(glm::lessThan(draw.pathTracingScattering,glm::vec3(0)))||!std::isfinite(draw.pathTracingAnisotropy)||std::abs(draw.pathTracingAnisotropy)>=.99f)throw std::invalid_argument("PT package: invalid medium coefficients");
        if((m.value("bounded_volume",false)||glm::any(glm::greaterThan(draw.pathTracingAbsorption+draw.pathTracingScattering,glm::vec3(0))))&&(draw.pathTracingIor<=1||draw.pathTracingKind==5))throw std::invalid_argument("PT package: medium requires a solid dielectric");
        if(draw.pathTracingKind==5&&(draw.pathTracingIor<=1||draw.pathTracingRoughness!=0))throw std::invalid_argument("PT package: thin dielectric requires IOR and smooth boundary");
        auto payload=std::make_shared<render::MaterialPayload>();if(m.contains("base_texture"))payload->images[0]=image(m["base_texture"]);
        if(m.contains("normal_texture")){payload->images[1]=image(m["normal_texture"]);draw.parameters.emissiveNormal.w=m.value("normal_strength",1.f);if(!std::isfinite(draw.parameters.emissiveNormal.w)||draw.parameters.emissiveNormal.w<0||draw.parameters.emissiveNormal.w>8)throw std::invalid_argument("PT package: invalid normal strength");}
        if(m.contains("orm_texture")){payload->images[2]=payload->images[3]=image(m["orm_texture"]);draw.parameters.factors.x=draw.parameters.factors.y=1;draw.pathTracingRoughnessTexture=draw.pathTracingIor>0&&draw.pathTracingKind!=5;}
        draw.pathTracingDiffuseTransmission=vector(m.value("diffuse_transmission",Json::array({0,0,0})));if(glm::any(glm::lessThan(draw.pathTracingDiffuseTransmission,glm::vec3(0)))||glm::any(glm::greaterThan(draw.pathTracingDiffuseTransmission,glm::vec3(1)))||(draw.pathTracingBsdfModel==3&&(draw.pathTracingIor>0||draw.pathTracingKind==5)))throw std::invalid_argument("PT package: invalid thin diffuse transmission");if(m.contains("transmission_texture"))draw.pathTracingTransmissionTexture=image(m["transmission_texture"]);
        draw.material=payload;materials.push_back(draw);}
    if(materials.size()>65536||j.at("draws").size()>1048576)throw std::length_error("PT package: too many materials/draws");
    std::map<std::tuple<uint64_t,uint32_t,uint64_t>,std::shared_ptr<const render::MeshPayload>> meshes;uint64_t totalVertices=0,uniqueVertices=0;
    for(auto &d:j.at("draws")){auto material=d.at("material").get<uint32_t>();if(material>=materials.size())throw std::invalid_argument("PT package: invalid material index");auto offset=d.at("offset").get<uint64_t>();auto count=d.at("vertices").get<uint32_t>();if(offset<8||(offset-8)%32||!count||count%3)throw std::invalid_argument("PT package: invalid triangle range");totalVertices+=count;if(totalVertices/3>=UINT32_MAX)throw std::length_error("PT package: instanced primitive IDs exceed 32 bits");auto tangentOffset=d.value("tangents_offset",UINT64_MAX);if(tangentOffset!=UINT64_MAX&&(tangentFile.empty()||tangentOffset<8||(tangentOffset-8)%16))throw std::invalid_argument("PT package: invalid tangent range");auto key=std::make_tuple(offset,count,tangentOffset);auto found=meshes.find(key);std::shared_ptr<const render::MeshPayload> mesh;
        if(found!=meshes.end())mesh=found->second;else{uniqueVertices+=count;if(uniqueVertices>(uint64_t(1)<<27))throw std::length_error("PT package: unique geometry budget exceeded");const auto geometryStarted=std::chrono::steady_clock::now();auto a=floats(binary,offset,uint64_t(count)*8);auto created=std::make_shared<render::MeshPayload>();created->vertices.reserve(count);created->indices.reserve(count);for(uint32_t i=0;i<count;++i){auto k=size_t(i)*8;created->vertices.push_back({{a[k],a[k+1],a[k+2]},{a[k+3],a[k+4],a[k+5]},{a[k+6],a[k+7]}});created->indices.push_back(i);}if(tangentOffset!=UINT64_MAX){auto t=floats(tangentFile,tangentOffset,uint64_t(count)*4);created->pathTracingTangents.reserve(count);for(uint32_t i=0;i<count;++i){auto k=size_t(i)*4;if(t[k+3]!=0&&t[k+3]!=1&&t[k+3]!=-1)throw std::invalid_argument("PT package: invalid tangent handedness");created->pathTracingTangents.emplace_back(t[k],t[k+1],t[k+2],t[k+3]);}}mesh=created;meshes[key]=mesh;geometrySeconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-geometryStarted).count();}
        auto draw=materials[material];draw.objectId=s.draws.size()+1;draw.mesh=mesh;draw.model=matrix(d.at("model"));s.draws.push_back(std::move(draw));}
    for(auto &l:j.value("lights",Json::array())){int type=l.at("type");if(type<0||type>2)throw std::invalid_argument("PT package: invalid light type");frame.lights.push_back({glm::vec4(vector(l.at("position")),type),glm::vec4(vector(l.at("color")),l.value("inner",0.f)),glm::vec4(vector(l.at("direction")),l.value("outer",0.f))});}
    if(j.contains("environment")){auto &e=j["environment"];auto w=e.at("width").get<uint32_t>(),h=e.at("height").get<uint32_t>();if(!w||!h||w>8192||h>4096)throw std::invalid_argument("PT package: invalid environment dimensions");auto a=floats(local(root,e.at("file")),0,uint64_t(w)*h*3);std::vector<glm::vec3> pixels;pixels.reserve(size_t(w)*h);for(size_t i=0;i<a.size();i+=3){if(a[i]<0||a[i+1]<0||a[i+2]<0)throw std::invalid_argument("PT package: negative environment radiance");pixels.emplace_back(a[i],a[i+1],a[i+2]);}result.environment=std::make_shared<Environment>(w,h,std::move(pixels));}
    if(j.contains("sun")){auto &sun=j["sun"];result.sunDirection=vector(sun.at("direction"));result.sunIrradiance=vector(sun.at("irradiance"));result.sunRadius=sun.at("radius");if(std::abs(glm::length(result.sunDirection)-1)>1e-3||!std::isfinite(result.sunRadius)||result.sunRadius<=0||result.sunRadius>.1f||glm::any(glm::lessThan(result.sunIrradiance,glm::vec3(0))))throw std::invalid_argument("PT package: invalid sun");}
    result.metadata={{"file",path},{"source",j.value("source",Json::object())},{"export",j.value("export",Json::object())},{"unique_mesh_ranges",meshes.size()},{"draws",s.draws.size()},{"materials",materials.size()},{"expanded_triangles",totalVertices/3}};
    if(j.contains("comparison"))result.metadata["comparison"]=j["comparison"];
    result.metadata["unique_vertices"]=uniqueVertices;result.metadata["load_timings"]={{"total_seconds",std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count()},{"manifest_parse_seconds",manifestSeconds},{"texture_decode_seconds",textureSeconds},{"unique_geometry_decode_seconds",geometrySeconds}};
    return result;
}
}
