#include "renderer/rhi/GpuSubdivision.h"
#include <algorithm>
#include <cmath>
#include <limits>
namespace render {
GpuSubdivision::GpuSubdivision(std::shared_ptr<rhi::GraphicsDevice> d,const std::string& dir,const std::vector<MeshVertex>& v,const std::vector<uint32_t>& i,const ImageRGBA8& height,uint32_t maximum):resources_(d),vertexCount_(uint32_t(v.size())),indexCount_(uint32_t(i.size())),maxLevel_(maximum){
    using namespace rhi;if(!d->computeLimits().supported || !maximum || maximum>32)throw std::invalid_argument("Subdivision requires compute and a level in 1..32");GpuMesh validate(d,v,i);const uint64_t capacity=uint64_t(i.size())*maximum*maximum;if(capacity>UINT32_MAX || capacity*32>d->bufferLimits().maxBufferSize)throw std::invalid_argument("Subdivision mesh exceeds backend allocation limit");mesh_=std::make_shared<GpuMesh>(d,uint32_t(capacity),uint32_t(capacity),validate.boundsMin()-glm::vec3(1),validate.boundsMax()+glm::vec3(1));vertices_=resources_.buffer({v.size()*32,BufferUsage::Storage,"Subdivision source vertices"},v.data());indices_=resources_.buffer({i.size()*4,BufferUsage::Storage,"Subdivision source indices"},i.data());
    const bool empty=height.pixels.empty() && !height.width && !height.height;if(!empty && (!height.width || !height.height || height.pixels.size()!=size_t(height.width)*height.height*4))throw std::invalid_argument("Subdivision height map invalid");auto tex=resources_.texture({empty?1u:height.width,empty?1u:height.height,Format::RGBA8UNorm,TextureUsage::Sampled|TextureUsage::CopyDestination,"Subdivision height map"});const uint8_t zero[]={0,0,0,255};d->writeTexture(tex,empty?zero:height.pixels.data(),empty?4:height.pixels.size());height_=resources_.view(tex);sampler_=resources_.sampler({Filter::Linear,AddressMode::Repeat});
    const auto p=dir+"/subdivide.comp";parametersLayout_={0,{{0,BindingType::UniformBuffer,ShaderStage::Compute,"SubdivisionParameters",32}}};inputsLayout_={1,{{0,BindingType::StorageRead,ShaderStage::Compute,"SourceVertices",4},{1,BindingType::StorageRead,ShaderStage::Compute,"SourceIndices",4},{2,BindingType::StorageWrite,ShaderStage::Compute,"SubdividedVertices",4},{3,BindingType::StorageWrite,ShaderStage::Compute,"SubdividedIndices",4},{4,BindingType::SampledTexture,ShaderStage::Compute,"heightMap",0}}};ComputePipelineDesc pipeline;pipeline.shader={p+".glsl",p+".metallib",p+".spv",p+".json","main0"};pipeline.bindings={parametersLayout_,inputsLayout_};pipeline.threads={64,1,1};pipeline_=resources_.computePipeline(pipeline);
}
void GpuSubdivision::update(uint32_t level,float scale){
    using namespace rhi;if(!level || level>maxLevel_ || !std::isfinite(scale) || std::abs(scale)>1)throw std::invalid_argument("Subdivision level/height outside bounds");if(level==level_ && scale==heightScale_)return;
    struct alignas(16) Parameters{glm::uvec4 counts;glm::vec4 settings;};Parameters p{{indexCount_/3,level,0,0},{scale,0,0,0}};Resources frame(resources_.device);auto data=frame.buffer({32,BufferUsage::Uniform,"Subdivision parameters"},&p);auto params=frame.bindings({parametersLayout_,{{0,data,0,32,{},{}}}});const size_t capacity=size_t(indexCount_)*maxLevel_*maxLevel_;auto inputs=frame.bindings({inputsLayout_,{{0,vertices_,0,size_t(vertexCount_)*32,{},{}},{1,indices_,0,size_t(indexCount_)*4,{},{}},{2,mesh_->vertexBuffer(),0,capacity*32,{},{}},{3,mesh_->indexBuffer(),0,capacity*4,{},{}},{4,{},0,0,height_,sampler_}}});const DrawIndexedIndirectArguments args{indexCount_*level*level,1,0,0,0};resources_.device->writeBuffer(mesh_->indirectBuffer(),0,20,&args);
    const uint32_t groups=((indexCount_/3)*level*level+63)/64,limit=resources_.device->computeLimits().maxGroups[0];if(groups>limit)throw std::invalid_argument("Subdivision dispatch exceeds workgroup count");auto commands=resources_.device->createCommandList();commands.dispatch(pipeline_,{params,inputs},{groups,1,1});resources_.device->submit(commands);level_=level;heightScale_=scale;
}
std::vector<MeshVertex> GpuSubdivision::readVertices(){std::vector<MeshVertex> v(size_t(indexCount_)*level_*level_);if(!v.empty())resources_.device->readBuffer(mesh_->vertexBuffer(),0,v.size()*32,v.data());return v;}
}
