#include "PT/ValidationScenes.h"
#include "PT/SubsurfaceMesh.h"
#include <cmath>
#include <glm/gtc/matrix_transform.hpp>
#include <iostream>
#include <stdexcept>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb/stb_image_write.h>
namespace {
void check(bool yes,const char *message){if(!yes)throw std::runtime_error(message);}
void sampling(){
    for(float g:{0.f,.65f,-.65f}){double integral=0;constexpr int bins=200000;for(int i=0;i<bins;++i)integral+=pt::phaseHG(-1+(i+.5f)*2/bins,g)*12.566370614359172/bins;check(std::abs(integral-1)<1e-4,"HG density is not normalized");pt::Random random(12);double mean=0;for(int i=0;i<100000;++i){auto d=pt::samplePhaseHG({0,0,1},g,random);check(std::abs(glm::length(d)-1)<1e-5,"HG direction is not unit");mean+=d.z;}check(std::abs(mean/100000-g)<.005,"HG samples disagree with anisotropy");}
    pt::Medium medium{{.4f,0,.2f},{.8f,0,1.4f},.2f};pt::Random random(17);glm::dvec3 boundary(0),collision(0);constexpr int n=200000;float length=1.3f;for(int i=0;i<n;++i){auto sample=pt::sampleMedium(medium,length,random);(sample.scattered?collision:boundary)+=glm::dvec3(sample.weight)/double(n);}auto T=pt::transmittance(medium.absorption+medium.scattering,length);glm::vec3 expected{medium.scattering.x/1.2f*(1-T.x),0,medium.scattering.z/1.6f*(1-T.z)};check(glm::length(boundary-glm::dvec3(T))<.006,"RGB boundary mixture estimator is biased");check(glm::length(collision-glm::dvec3(expected))<.006,"RGB collision mixture estimator is biased");auto pure=pt::sampleMedium({{.2f,0,.4f},{0,0,0},0},2,random);check(!pure.scattered&&glm::length(pure.weight-glm::exp(-glm::vec3(.2f,0,.4f)*2.f))<1e-6,"Absorption fast path changed");check(glm::length(pt::transmittance({1,0,2},INFINITY)-glm::vec3(0,1,0))==0,"Infinite zero-extinction channel changed");
}
void closure(){auto fixture=pt::makeMediumValidationScene(8,8,true);auto mesh=*fixture.snapshot.draws[0].mesh;auto closed=pt::closeSubsurfaceMesh(mesh,4);check(closed.weldedVertices==16&&closed.filledHoles==0,"Closed mesh welding changed topology");mesh.indices.resize(mesh.indices.size()-6);auto repaired=pt::closeSubsurfaceMesh(mesh,4);check(repaired.filledHoles==1&&repaired.boundaryEdges==0,"Missing face was not closed");auto nonmanifold=mesh;nonmanifold.indices.insert(nonmanifold.indices.end(),mesh.indices.begin(),mesh.indices.begin()+3);bool rejected=false;try{pt::closeSubsurfaceMesh(nonmanifold,4);}catch(const std::invalid_argument &){rejected=true;}check(rejected,"Non-manifold volume accepted");}
void transport(){auto fixture=pt::makeMediumValidationScene(8,8,true);pt::CpuScene scene(fixture.snapshot);scene.environment=std::make_shared<pt::Environment>(8,4,std::vector<glm::vec3>(32,glm::vec3(1)));glm::dvec3 mean(0);uint64_t rays=0,events=0;constexpr int samples=30000;for(int i=0;i<samples;++i){pt::Random random(i+51);mean+=glm::dvec3(scene.trace({0,0,4},{0,0,-1},random,128,rays,&events))/double(samples);}std::cout<<"Conservative random walk energy "<<mean.x<<", scatter events "<<events<<'\n';check(glm::length(mean-glm::dvec3(1))<.08,"Conservative BSSRDF lost/gained energy");check(events>samples,"Random walk was not exercised");
    auto overlapping=fixture.snapshot;auto merged=std::make_shared<render::MeshPayload>(*overlapping.draws[0].mesh);const auto source=*merged;for(auto v:source.vertices){v.position+=glm::vec3(.4f);merged->vertices.push_back(v);}for(auto index:source.indices)merged->indices.push_back(index+uint32_t(source.vertices.size()));overlapping.draws[0].mesh=merged;pt::CpuScene unionScene(overlapping);std::array<uint32_t,8> winding{};auto unionIds=unionScene.initialMedia({0,0,0},&winding);check(unionIds[0]==1&&winding[0]==2,"Self-overlap camera winding was lost");unionScene.environment=scene.environment;pt::Random overlapRandom(19);uint64_t overlapEvents=0;auto overlapValue=unionScene.trace({0,0,0},{0,0,1},overlapRandom,128,rays,&overlapEvents);check(std::isfinite(glm::length(overlapValue)),"Overlapping scan generated invalid transport");
    auto nine=fixture.snapshot;nine.draws.clear();for(int i=0;i<9;++i){auto draw=fixture.snapshot.draws[0];draw.model=glm::scale(glm::mat4(1),glm::vec3(1+i));nine.draws.push_back(draw);}pt::CpuScene deep(nine);bool overflow=false;try{deep.initialMedia({0,0,0});}catch(const std::runtime_error &){overflow=true;}check(overflow,"More than eight camera media accepted");
    auto nested=pt::makeMediumValidationScene(8,8);pt::CpuScene media(nested.snapshot);auto ids=media.initialMedia({0,0,0});check(ids[0]==1&&ids[1]==2&&ids[2]==0,"Nested water/jade camera media order");check(glm::length(media.initialAbsorption({0,0,0})-glm::vec3(2,.1f,.8f))<1e-6,"Solid failed to override water");auto exported=media.exportData();check(exported.materials[1].scattering.w==.3f&&exported.materials[0].optics.y==1,"GPU volume metadata mismatch");bool rejected=false;try{media.validateBidirectional();}catch(const std::invalid_argument &){rejected=true;}check(rejected,"Surface BDPT accepted volume vertices");for(int mode=0;mode<4;++mode){auto bad=nested.snapshot;if(mode==0)bad.draws[0].pathTracingScattering.x=-1;if(mode==1)bad.draws[0].pathTracingAnisotropy=1;if(mode==2)bad.draws[0].pathTracingScattering.x=NAN;if(mode==3)bad.draws[0].pathTracingIor=0;rejected=false;try{pt::CpuScene invalid(bad);}catch(const std::invalid_argument &){rejected=true;}check(rejected,"Invalid medium was accepted");}
}
}
int main(){try{sampling();closure();transport();std::cout<<"RGB free flight, HG, closed scan, conservative BSSRDF and nested media passed\n";return 0;}catch(const std::exception &error){std::cerr<<error.what()<<'\n';return 1;}}
