#version 450
#extension GL_GOOGLE_include_directive : require
#include "atmosphere-common.glsl"
layout(local_size_x=8,local_size_y=8) in;
layout(set=1,binding=0,rgba32f) writeonly uniform image2D transmittanceTexture;
void main() {
    ivec2 pixel=ivec2(gl_GlobalInvocationID.xy);if(any(greaterThanEqual(pixel,dimensions.xy)))return;
    vec2 x=vec2(pixel)/vec2(dimensions.xy-1);
    float H=sqrt(atmosphere.top_radius*atmosphere.top_radius-atmosphere.bottom_radius*atmosphere.bottom_radius),rho=H*x.y;
    float r=sqrt(rho*rho+atmosphere.bottom_radius*atmosphere.bottom_radius);
    float dmin=atmosphere.top_radius-r,dmax=rho+H,d=mix(dmin,dmax,x.x);
    float mu=d<1e-5?1.0:clamp((H*H-rho*rho-d*d)/(2.0*r*d),-1.0,1.0);
    float length=distanceTop(r,mu);vec3 optical=vec3(0);
    const int steps=96;
    for(int i=0;i<steps;++i) {
        float a=float(i)/float(steps),b=float(i+1)/float(steps),start=a*a*length,end=b*b*length;
        float ri=radiusAlongRay(r,mu,(start+end)*.5);vec3 rayleigh,mie,extinction;
        coefficients(ri-atmosphere.bottom_radius,rayleigh,mie,extinction);optical+=extinction*(end-start);
    }
    imageStore(transmittanceTexture,pixel,vec4(exp(-optical),1));
}
