#version 450
#extension GL_GOOGLE_include_directive : require
layout(local_size_x=8,local_size_y=8) in;
#include "cloud-parameters.glsl"
#include "cloud-volume-sampling.glsl"
layout(set=1,binding=0) uniform sampler2D cloudDistanceSource;
layout(set=1,binding=1,rgba8) writeonly uniform image2D cloudDistance;
void main(){
    ivec2 at=ivec2(gl_GlobalInvocationID.xy);if(any(greaterThanEqual(at,imageSize(cloudDistance))))return;
    ivec3 p=ivec3(at%32,(at.y/32)*8+at.x/32);vec4 current=texelFetch(cloudDistanceSource,at,0);
    vec3 distance=round(current.rga*255.);
    for(int z=-1;z<=1;z++)for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){
        ivec3 q=p+ivec3(x,y,z);if(any(lessThan(q,ivec3(0))) || any(greaterThanEqual(q,ivec3(32))))continue;
        distance=min(distance,round(texelFetch(cloudDistanceSource,cloudBrickTexel(q),0).rga*255.)+1.);
    }
    imageStore(cloudDistance,at,vec4(distance.xy/255.,current.b,distance.z/255.));
}
