#version 450
#extension GL_GOOGLE_include_directive : require
layout(local_size_x=8,local_size_y=8) in;
#include "cloud-parameters.glsl"
layout(set=1,binding=0,std430) buffer CloudDispatch {uint groupsX,groupsY,groupsZ;};
layout(set=1,binding=1,rgba16f) writeonly uniform image2D cloudRaw;
layout(set=1,binding=2,rgba32f) writeonly uniform image2D cloudRawDepth;
void main(){ivec2 p=ivec2(gl_GlobalInvocationID.xy);if(all(equal(p,ivec2(0)))){groupsX=0;groupsY=1;groupsZ=1;}
    if(any(greaterThanEqual(p,cloudGrid.xy)))return;
    imageStore(cloudRaw,p,vec4(0,0,0,1));imageStore(cloudRawDepth,p,vec4(0));
}
