#version 450
#extension GL_GOOGLE_include_directive : require
#include "terrain-parameters.glsl"
#define MIN_LEVEL 0
#define MAX_LEVEL 5





#define MIN_DISTANCE 5
#define MAX_DISTANCE 50

#define INITIAL_NODE_NUM 5



layout(local_size_x=1,local_size_y=1,local_size_z=1) in;


















struct Node{
    uvec2 pos;
};
struct FinalNode{
    uvec3 pos;
};

layout(set=1,binding=2,std140) buffer FinalNodeList{
    uint finalNodeCnt;
    uint one;
    uint one_;
    uvec3 finalNode[];
};

struct NodeInfo{
    uint isLeaf;
};
layout(set=1,binding=1,std430) buffer NodeDescriptor{
    NodeInfo info[];
};

uint GetNodeID(uvec3 nodeLoc){
    uint nodeIdOffsetLOD[6] = {8525,2125,525,125,25,0};
    uint nodeCountLOD[6] = {160,80,40,20,10,5};
    return nodeIdOffsetLOD[nodeLoc.z] + nodeLoc.y * nodeCountLOD[nodeLoc.z] + nodeLoc.x;
}

layout(set=1,binding=3,std430) readonly buffer InQueue{
    uint nodeCnt;
    uint one;
    uint one_;
    uvec2 nodes[];
}inQueue;

layout(set=1,binding=4,std430) buffer OutQueue{
    uint nodeCnt;
    uint one;
    uint one_;
    uvec2 nodes[];
}outQueue;






















int GetLODLevel(vec3 Position[4]){
    vec4 eyeSpacePos[4];

    for(int i =0;i<4;i++){
        eyeSpacePos[i] = view * model * vec4(Position[i],1.0f);
    }


    float pointDistance[4];
    for(int i= 0;i<4;i++){
        pointDistance[i] = length(eyeSpacePos[i].xyz);
    }

    float level[4];
    for(int i=0;i<4;i++){


        float level_ = 0;
        float d = pointDistance[i];
        if(d < MIN_DISTANCE){
            level_ = MIN_LEVEL;
        }else if (d > MAX_DISTANCE){
            level_ = MAX_LEVEL;
        }else{

            level_ = (d-MIN_DISTANCE) / (MAX_DISTANCE-MIN_DISTANCE) * (MAX_LEVEL-MIN_LEVEL-1) + MIN_LEVEL + 1;
        }
        level[i] = level_;
    }

    float maxLevel = min(level[0],min(level[1],min(level[2],level[3])));
    maxLevel = clamp(maxLevel, MIN_LEVEL, MAX_LEVEL);
    return int(maxLevel);
}

bool needCulling(vec3 Position[4]){

    vec4 NDC[4];

    for(int i=0;i<4;i++){
        NDC[i] = viewProjection * model * vec4(Position[i],1.0f);
    }
    if(NDC[0].w < 0.0f && NDC[1].w <0.0f && NDC[2].w <0.0f && NDC[3].w < 0.0f){
        return true;
    }
    int code[4];
    for(int i=0;i<4;i++){
        NDC[i] = NDC[i] / NDC[i].w;
        code[i] = 0;

        if(NDC[i].x < -1.f){
            code[i] += (1<<4);
        }else if (NDC[i].x <= 1.f){
        }else{
            code[i] += (1<< 5);
        }

        if(NDC[i].y < -1.f){
            code[i] += (1<<2);
        }else if (NDC[i].y <= 1.f){
        }else{
            code[i] += (1<<3);
        }

        if(NDC[i].z < -1.f){
            code[i] += (1<<0);
        }else if (NDC[i].z <= 1.f){
        }else{
            code[i] += (1<<1);
        }
    }
    int AND = code[0] & code[1] & code[2] & code[3];
    int x_ = (AND >> 4);
    int y_ = (AND >> 2)%4;
    int z_ = AND % 4;
    if(x_ > 0 || y_ >0 || z_ > 0)
        return true;
    return false;

}

void generateLODData(uvec2 nodeLoc,uint currentLod){







    uint nodeAllNum = INITIAL_NODE_NUM * (1 << currentLod);
    uvec2 offset[4] = {
        uvec2(0,0),
        uvec2(1,0),
        uvec2(1,1),
        uvec2(0,1)
    };
    vec2 uv[4];
    vec3 Position[4];
    for(int i =0;i<4;i++){
        uv[i] = vec2(nodeLoc + offset[i]) / float(nodeAllNum);
        Position[i] = vec3(2 * uv[i].x -1,0.0f,2 * uv[i].y-1);
    }



    for(int i= 0;i<4;i++){
        float height = sampleHeight(uv[i]);

        Position[i].y = height;
    }







    int currentLevel = GetLODLevel(Position);
    if(currentLevel + currentLod < MAX_LEVEL){



        uint curNodeIndex = atomicAdd(outQueue.nodeCnt,4);
        outQueue.nodes[curNodeIndex] = nodeLoc * 2;
        outQueue.nodes[curNodeIndex+1] = nodeLoc * 2 + uvec2(1,0);
        outQueue.nodes[curNodeIndex+2] = nodeLoc * 2 + uvec2(1,1);
        outQueue.nodes[curNodeIndex+3] = nodeLoc * 2 + uvec2(0,1);

        uint indexID = GetNodeID(uvec3(nodeLoc,MAX_LEVEL-currentLod));
        info[indexID].isLeaf = 0;
    }else{

        uint curFinalNode = atomicAdd(finalNodeCnt,1);

        finalNode[curFinalNode] = uvec3(nodeLoc,MAX_LEVEL-currentLod);
        info[GetNodeID(uvec3(nodeLoc,MAX_LEVEL-currentLod))].isLeaf = 1;
    }
}

void main(){

    uint nodeIndex = uint(gl_WorkGroupID.x);




    if(nodeIndex<inQueue.nodeCnt)generateLODData(inQueue.nodes[nodeIndex],currentLOD);
}
