#version 450
#extension GL_GOOGLE_include_directive : require
#include "virtual-texture.glsl"
layout(local_size_x=16,local_size_y=1,local_size_z=1)in;
layout(set=0,binding=0,std430) writeonly buffer VtResults {vec4 result[];};
layout(set=0,binding=1) uniform sampler2D atlas;
layout(set=0,binding=2) uniform sampler2D pageTable;
layout(set=0,binding=3,std430) readonly buffer VtSamples {vec4 samples[];};
void main(){uint i=gl_GlobalInvocationID.x;result[i]=virtualSampleLevel(atlas,pageTable,samples[i].xy,int(samples[i].z));}
